Models/APICall/ApiRoot.cs
using GamingApi.Models.APICall;
using System.Collections.Generic;

namespace WebApplication2.Models.APICall
{
    public class ApiRoot
    {
        public int id { get; set; }
        public List<int> age_ratings { get; set; }
        public int category { get; set; }
        public Cover cover { get; set; }
        public int created_at { get; set; }
        public List<int> external_games { get; set; }
        public string name { get; set; }
        public double popularity { get; set; }
        public double rating { get; set; }
        public int rating_count { get; set; }
        public List<ReleaseDate> release_dates { get; set; }
        public List<int> similar_games { get; set; }
        public string slug { get; set; }
        public string summary { get; set; }
        public List<int> tags { get; set; }
        public List<int> themes { get; set; }
        public double total_rating { get; set; }
        public int total_rating_count { get; set; }
        public int updated_at { get; set; }
        public string url { get; set; }
        public List<int> websites { get; set; }
        public string checksum { get; set; }

    }
}

Models/APICall/Cover.cs
namespace GamingApi.Models.APICall
{
    public class Cover
    {
        public int id { get; set; }
        public bool alpha_channel { get; set; }
        public bool animated { get; set; }
        public int game { get; set; }
        public int height { get; set; }
        public string image_id { get; set; }
        public string url { get; set; }
        public int width { get; set; }
        public string checksum { get; set; }
        public string imgPrefix { get; set; } = ".jpg";
    }
}

Models/APICall/ReleaseDate.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;

namespace GamingApi.Models.APICall
{
    public class ReleaseDate
    {
        public int id { get; set; }
        public int category { get; set; }
        public int created_at { get; set; }
        public int date { get; set; }
        public int game { get; set; }
        public string human { get; set; }
        public int m { get; set; }
        public int platform { get; set; }
        public int region { get; set; }
        public int updated_at { get; set; }
        public int y { get; set; }
        public string checksum { get; set; }

    }
}

Models/CSharp/FirstClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models.CSharp
{
    public class FirstClass
    {
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

Models/CSharp/IInterface.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models.CSharp
{
    public interface IInterface
    {
        public void ShowValue();
    }
}

Models/CSharp/MyInterface.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models.CSharp
{
    public class MyInterface
    {
        public int Interface { get; set; } = 1;
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/APIViewModel.cs
using System.Collections.Generic;
using WebApplication2.Models.APICall;

namespace GamingApi.ViewModels
{
    public class APIViewModel
    {
      public List<ApiRoot> apiRoot { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using GamingApi.Models.APICall;
using GamingApi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication2.Models;
using WebApplication2.Models.APICall;
using WebApplication2.Models.CSharp;
using WebApplication2.Services;

namespace WebApplication2.Controllers
{

    public class HomeController : Controller
    {
        // dependancy injection
        private readonly ILogger<HomeController> _logger;
        private readonly IApiService _apiService;


        ReleaseDate rd = new ReleaseDate();

        public HomeController(ILogger<HomeController> logger, IApiService apiService)
        {
            _logger = logger;
            _apiService = apiService;
        }
 

        public IActionResult Index()
        {
            var response = _apiService.GetGames<ApiRoot>();
            

            

            return View(new APIViewModel
            {
                apiRoot = response
            });
        }

       
        

        public IActionResult FirstView()
        {
            var response = _apiService.GetGames<ApiRoot>();

            return View(new APIViewModel
            {
                apiRoot = response
            }
            );
        }

        // for devwebs tutorial
        private async Task<IApiService> Getsomething()
        {
            return await Task.FromResult(_apiService);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewComponents/FirstViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebApplication2.Services;

namespace GamingApi.ViewComponents
{
    public class FirstViewComponent : ViewComponent
    {
        // dependancy injection
        private IApiService _apiService;

        public FirstViewComponent(IApiService service)
        {
            _apiService = service;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var myItem = await Getsomething();
            return View("Default", myItem);
        }

        private async Task<IApiService> Getsomething()
        {
            return await Task.FromResult(_apiService);
        }

    }
}

Views/Home/FirstView.cshtml
@model GamingApi.ViewModels.APIViewModel
@{
    ViewData["Title"] = "FirstView";
}

<div class="text-center">
    <h4 class="display-4"> Coming soon on <i class="fab fa-xbox"></i> </h4>

    <table class="table table-striped table-hover table-dark" id="myTable">
        <thead>
            <tr>
                <th>
                    Game
                </th>
                <th>
                    Release Date
                </th>
                <th>
                    Cover URL
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.apiRoot.OrderByDescending(m => m.name).ThenBy(m => m.total_rating))
            {
                <tr>
                    <td>
                        <a style="color:white; font-weight:bold;" target="_blank" href="@Html.DisplayFor(modelItem => item.url)">@Html.DisplayFor(modelItem => item.name) </a>
                    </td>
                    <td>

                        @foreach (var i in item.release_dates)
                        {
                            @Html.DisplayFor(modelItem => i.human)<br>
                        }

                    </td>
                    <td>
                        <img src="https://images.igdb.com/igdb/image/upload/t_cover_med/@Html.DisplayFor(modelItem => item.cover.image_id)@Html.DisplayFor(modelItem => item.cover.imgPrefix)" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@model GamingApi.ViewModels.APIViewModel

@{
    ViewData["Title"] = "Home Page";
}
<style>
    td {
        vertical-align: middle !important;
    }
</style>

<div class="text-center">
    <h4 class="display-4"> Coming soon on <i class="fab fa-xbox"></i> </h4>

    <table class="table table-striped table-hover table-dark" id="myTable">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Release Date
                </th>
                <th>
                    Cover URL
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.apiRoot.OrderByDescending(m => m.name))
            {
                <tr>
                    <td>
                        <a style="color:white; font-weight:bold;" target="_blank" href="@Html.DisplayFor(modelItem => item.url)">@Html.DisplayFor(modelItem => item.name) </a>
                    </td>
                    <td>

                        @foreach (var i in item.release_dates)
                        {
                            @Html.DisplayFor(modelItem => i.human)<br>
                        }

                    </td>
                    <td>
                        <img src="https://images.igdb.com/igdb/image/upload/t_cover_med/@Html.DisplayFor(modelItem => item.cover.image_id)@Html.DisplayFor(modelItem => item.cover.imgPrefix)" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Shared/Components/First/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model WebApplication2.Services.IApiService

   

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*<p>@Component.InvokeAsync("First")</p>*@
            &copy; 2020 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>